import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#111', alignItems: 'center' },
  map: { width: '100%', height: '100%' },

  // Login Ekranı
  loginOverlay: { flex: 1, width: '100%', backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', alignItems: 'center' },
  loginBox: { width: '85%', backgroundColor: 'rgba(30,30,30,1)', padding: 25, borderRadius: 15, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.5, shadowRadius: 10 },
  input: { backgroundColor: 'rgba(255,255,255,0.06)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', color: 'white', paddingVertical: 14, paddingHorizontal: 16, borderRadius: 14, marginBottom: 12, fontSize: 15 },
  connectButton: { backgroundColor: '#4CAF50', padding: 15, borderRadius: 14, alignItems: 'center', marginTop: 10, shadowColor: '#4CAF50', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.35, shadowRadius: 14, elevation: 6 },
  connectButtonRed: { backgroundColor: '#ff3b30', shadowColor: '#ff3b30' },
  connectButtonText: { color: 'white', fontSize: 18, fontWeight: 'bold' },

  // Giriş / Kayıt / Profil ortak alan bileşenleri
  authFieldWrap: { position: 'relative', width: '100%' },
  authFieldIconLeft: { position: 'absolute', left: 14, top: 16, zIndex: 1 },
  authFieldIconRight: { position: 'absolute', right: 14, top: 14 },
  authHeading: { color: '#9c9aa4', fontSize: 12.5, textAlign: 'center', marginBottom: 18 },
  authSwitchRow: { marginTop: 18, alignItems: 'center' },
  authSwitchText: { color: '#9c9aa4', fontSize: 13 },
  authSwitchAction: { color: '#ff3b30', fontWeight: '800' },

  uploadZone: { borderWidth: 1.5, borderStyle: 'dashed', borderColor: 'rgba(255,255,255,0.22)', borderRadius: 16, padding: 12, marginTop: 6, marginBottom: 16 },
  uploadHintText: { color: '#ff3b30', fontSize: 12, fontWeight: '700', textAlign: 'center', marginBottom: 10 },
  uploadPreviewWrap: { position: 'relative', borderRadius: 12, overflow: 'hidden', marginBottom: 10 },
  uploadCheckBadge: { position: 'absolute', top: 6, right: 6, width: 20, height: 20, borderRadius: 10, backgroundColor: '#4CAF50', justifyContent: 'center', alignItems: 'center' },
  uploadRow: { flexDirection: 'row', gap: 8 },
  uploadBtn: { flex: 1, backgroundColor: 'rgba(255,255,255,0.06)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', padding: 12, borderRadius: 12, alignItems: 'center' },
  uploadBtnText: { color: '#fff', fontSize: 11, fontWeight: '700', marginTop: 6 },

  profileSheetOverlay: { flex: 1, width: '100%', backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  profileSheet: { backgroundColor: '#1e1e1e', borderTopLeftRadius: 26, borderTopRightRadius: 26, paddingHorizontal: 20, paddingTop: 10, paddingBottom: 30, alignItems: 'center' },
  profileSheetAvatar: { width: 56, height: 56, borderRadius: 28, marginRight: 0, marginBottom: 16, alignSelf: 'center' },
  sheetActionsRow: { flexDirection: 'row', gap: 10, width: '100%', marginTop: 6 },
  ghostButton: { flex: 1, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)', borderRadius: 14, paddingVertical: 15 },
  ghostButtonText: { color: '#fff', fontWeight: '700', fontSize: 14 },

  // Ana Ekran (Home) Görünümü
  topBar: { position: 'absolute', top: 60, left: 20, right: 20, zIndex: 100, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  profileCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.06)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', paddingVertical: 8, paddingHorizontal: 10, borderRadius: 16, maxWidth: '78%' },
  avatarCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#4CAF50', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  avatarText: { color: '#0a0a0a', fontWeight: '800', fontSize: 15 },
  profileName: { color: '#fff', fontSize: 14, fontWeight: '700' },
  plateBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#4CAF50', alignSelf: 'flex-start', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, marginTop: 4 },
  plateBadgeText: { color: '#0a0a0a', fontSize: 10, fontWeight: '800', marginLeft: 3 },
  iconButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.06)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', justifyContent: 'center', alignItems: 'center' },

  topBanner: { position: 'absolute', top: 50, width: '90%', backgroundColor: '#1a1a1a', borderRadius: 16, padding: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', zIndex: 10, borderWidth: 1, borderColor: '#ff3b30', shadowColor: '#ff3b30', shadowOpacity: 0.35, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 8 },
  bannerIconWrap: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,59,48,0.15)', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  bannerInfo: { flex: 1 },
  bannerTitle: { color: '#ff3b30', fontWeight: '900', fontSize: 14, letterSpacing: 0.3 },
  bannerSubtitle: { color: 'rgba(255,255,255,0.75)', fontSize: 13, marginTop: 2 },
  joinButton: { backgroundColor: '#ff3b30', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12 },
  joinButtonText: { color: 'white', fontWeight: '800', fontSize: 13 },

  homeSosContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', width: '100%' },
  sosButtonBox: { width: 150, height: 150, justifyContent: 'center', alignItems: 'center' },
  sosTouchable: { width: 150, height: 150, justifyContent: 'center', alignItems: 'center' },
  radarRing: { position: 'absolute', width: 150, height: 150, borderRadius: 75, borderWidth: 2, borderColor: '#ff3b30' },
  sosButton: { width: 150, height: 150, borderRadius: 75, backgroundColor: '#ff3b30', justifyContent: 'center', alignItems: 'center', shadowColor: '#ff3b30', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.8, shadowRadius: 20, elevation: 10 },
  sosText: { color: 'white', fontSize: 32, fontWeight: '900', marginTop: 2 },

  bottomBar: { position: 'absolute', bottom: 40, left: 20, zIndex: 100 },
  editProfileBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.08)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)', paddingHorizontal: 16, paddingVertical: 11, borderRadius: 22 },
  editProfileText: { color: '#fff', fontWeight: '700', fontSize: 13, marginLeft: 6 },

  // Oda (Room) Görünümü
  roomContainer: { flex: 1, backgroundColor: '#111' },
  roomHeader: { height: 100, paddingTop: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 15, backgroundColor: '#111', gap: 10 },
  roomTitleWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  liveDot: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#ff3b30' },
  roomTitle: { color: 'white', fontSize: 13, fontWeight: '800', letterSpacing: 0.5 },
  endButton: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#ff3b30', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 9 },
  endButtonText: { color: '#fff', fontWeight: '800', fontSize: 11 },

  roomMapBox: { flex: 1, backgroundColor: '#333' },
  occupancyChip: { position: 'absolute', top: 12, left: 12, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(12,12,15,0.74)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12 },
  occupancyDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#4CAF50' },
  occupancyChipText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  mapControls: { position: 'absolute', top: 12, right: 12, gap: 8 },
  mapControlBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(12,12,15,0.74)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)', justifyContent: 'center', alignItems: 'center' },
  chatFab: { position: 'absolute', bottom: 12, left: 12, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(12,12,15,0.8)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 18 },
  chatFabText: { color: '#fff', fontWeight: '700', fontSize: 12 },

  pttBox: { backgroundColor: '#161616', borderTopLeftRadius: 30, borderTopRightRadius: 30, alignItems: 'center', padding: 20, paddingTop: 12, paddingBottom: 40, minHeight: 280 },
  pttDragHandle: { width: 36, height: 4, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.18)', marginBottom: 16 },
  pttStatusRow: { flexDirection: 'row', alignItems: 'center', width: '100%', justifyContent: 'center', marginBottom: 10 },
  pttStatusDot: { width: 10, height: 10, borderRadius: 5, marginRight: 8 },
  pttStatusTextNew: { color: 'white', fontSize: 16, fontWeight: 'bold', marginRight: 20 },
  pttTimerText: { color: '#ccc', fontSize: 16, fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  pttButtonContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', width: '100%' },
  pttButton: { width: 130, height: 130, borderRadius: 65, justifyContent: 'center', alignItems: 'center' },
  pttButtonInactive: { backgroundColor: '#333', borderWidth: 2, borderColor: '#444' },
  pttButtonRecording: { backgroundColor: '#ff3b30', shadowColor: '#ff3b30', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.8, shadowRadius: 20, elevation: 15 },
  pttButtonLocked: { backgroundColor: '#2a0d0d', borderColor: '#4d1414' },
  lockChip: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#1a1a1a', borderWidth: 1, borderColor: '#ff3b30', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8, marginBottom: 30 },
  lockChipText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  eqRow: { width: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4 },
  eqBar: { width: 4, backgroundColor: '#ff3b30', borderRadius: 2 },

  sosMarkerContainer: { alignItems: 'center', justifyContent: 'center', position: 'relative' },
  sosMarkerRing: { position: 'absolute', width: 54, height: 54, borderRadius: 27, backgroundColor: 'rgba(255,59,48,0.25)' },
  sosBadge: { backgroundColor: '#ff3b30', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 10, borderWidth: 2, borderColor: 'white', zIndex: 2, elevation: 5, marginBottom: -5 },
  sosBadgeText: { color: 'white', fontSize: 10, fontWeight: 'bold' },
  carIcon: { fontSize: 36 },
  taxiMarker: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 3, shadowOffset: { width: 0, height: 2 }, elevation: 3 },

  chatModalContainer: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.85)' },
  chatBox: { backgroundColor: '#1a1a1a', height: '70%', borderTopLeftRadius: 25, borderTopRightRadius: 25, display: 'flex' },
  chatDragHandle: { width: 40, height: 5, backgroundColor: '#555', borderRadius: 3, alignSelf: 'center', marginTop: 15, marginBottom: 5 },
  chatHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingBottom: 15, borderBottomWidth: 1, borderColor: '#333' },
  chatHeaderTitle: { fontSize: 18, fontWeight: 'bold', color: 'white' },
  chatCloseText: { color: '#ff3b30', fontSize: 16 },
  chatRow: { flexDirection: 'row', marginBottom: 15, alignItems: 'flex-start' },
  chatRowMe: { justifyContent: 'flex-end' },
  chatRowOther: { justifyContent: 'flex-start' },
  chatAvatarOther: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#333', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  chatAvatarMe: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#333', justifyContent: 'center', alignItems: 'center', marginLeft: 10 },
  chatBubble: { padding: 12, borderRadius: 15 },
  chatBubbleMe: { backgroundColor: '#d32f2f', borderTopRightRadius: 4 },
  chatBubbleOther: { backgroundColor: '#2a2a2a', borderTopLeftRadius: 4 },
  chatSenderName: { fontSize: 13, color: '#ff5252', marginBottom: 4, fontWeight: 'bold' },
  chatContent: { color: '#fff', fontSize: 15 },
  chatMetaRow: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  chatTime: { fontSize: 11, color: '#888' },
  chatPlayIconBtn: { marginRight: 10, justifyContent: 'center', alignItems: 'center' },
  audioMessageContainer: { minWidth: 150, paddingVertical: 5 },
  audioMessageRow: { flexDirection: 'row', alignItems: 'center' },
  waveformBox: { flex: 1 },
  audioDurationText: { color: '#aaa', fontSize: 11, fontWeight: 'bold', marginTop: 5, alignSelf: 'flex-start' },
  onlineUsersRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 10 },
  onlineDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#4CAF50', marginRight: 8 },
  onlineUsersText: { color: '#888', fontSize: 12 },
  chatInputContainer: { flexDirection: 'row', alignItems: 'center', padding: 15, paddingBottom: 30, backgroundColor: '#1a1a1a', borderTopWidth: 1, borderColor: '#333' },
  chatAttachmentButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#2a2a2a', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  chatInput: { flex: 1, backgroundColor: '#2a2a2a', borderRadius: 22, paddingHorizontal: 15, paddingVertical: 12, color: 'white', fontSize: 15 },
  chatSendButton: { backgroundColor: '#007aff', height: 44, paddingHorizontal: 20, borderRadius: 22, justifyContent: 'center', alignItems: 'center', marginLeft: 10 },
  chatSendText: { color: 'white', fontWeight: 'bold', fontSize: 14 },

});
